### ISSUE TITLE
Error parsing SYSTEM hive from Win8.1 x64

### ISSUE THREAD

**Issue by azerg** [libyal/libregf#4]
![screenshot_1](https://cloud.githubusercontent.com/assets/8020510/6964493/5a73a91c-d952-11e4-96b2-a9568473704b.png)

Sample SYSTEM hive file if needed: https://onedrive.live.com/redir?resid=83cbbef6b31667e8!8242&authkey=!AAqSoudsdHI9zi4&ithint=file%2c

**Comment by joachimmetz** [comment]
Thanks I'll have a look when time permits.

**Comment by joachimmetz** [comment]
The reason for the error is trailing zero byte values at the end of the file.
```
007ffff0  3c 22 08 4e 91 a2 91 d0  11 d4 22 64 00 00 00 00  |<".N......"d....|
00800000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00880000
```

I'll update the documentation and add support for this edge case.

**Comment by azerg** [comment]
:+1: 
I'm going to test sln with hive files from the other Win8.1_x64 images, but i'm not sure that my one was not dumped properly. Anyway it might be possible (in theory)

**Comment by azerg** [comment]
Other samples were parsed successfully with ur libregf.
So my first source file might be corrupted :bug: Anyway other tool (RegView) parses it ok.

**Comment by joachimmetz** [comment]
Wrong button ;) 

> Anyway other tool (RegView) parses it ok.

As far as I know RegView uses the Windows API so maybe it's a yet unobserved part of the format. Without official documentation who is going to tell for sure.

**Comment by joachimmetz** [comment]
I finally got around to looking at this file again.

Additional indication this file is corrupt:
```
libregf_key_item_read_sub_keys_list: unable to retrieve hive bin at offset: 8634840.
```

which is fall points to an offset inside the "unused hive bin data".

**Comment by joachimmetz** [comment]
File contains various more places with corruption, though I've [changed](https://github.com/libyal/libregf/commit/69297f39c0ce15f870d28d738945cb38db18e0cc) libregf to compensate for the corruption and mark (at the moment most of) the corresponding keys and values as corrupted.

**Comment by joachimmetz** [comment]
Closing issue.
