### ISSUE TITLE
Full regf specifications

### ISSUE THREAD

**Issue by fereh** [libyal/libregf#7]
Fortunately, @msuhanov has already done all the hard work of reverse engineering for you.
All registry hive specifications can be found at [msuhanov/regf](https://github.com/msuhanov/regf).

**Comment by joachimmetz** [comment]
@fereh what is your point?

[msuhanov/regf](https://github.com/msuhanov/regf/blob/master/Windows%20registry%20file%20format%20specification.md#additional-sources-of-information) is based on earlier work, including the working document of this project

**Comment by fereh** [comment]
I just saw in your source code that you had a lot of unknown values.
