### ISSUE TITLE
input folder not being created inside test folder after make check

### ISSUE THREAD

**Issue by Anirmita** [libyal/libregf#9]
[Screenshot from 2019-03-20 17-46-52](https://user-images.githubusercontent.com/29912669/54672168-86d8ca00-4b1d-11e9-8aec-11301c5dbcfd.png)
Screenshot attached. Please check.

**Comment by joachimmetz** [comment]
That is correct. You'll to create the input folder yourself and put in the test files

per https://github.com/libyal/libregf/wiki/Testing
`Note that no test files are provided by the project.`

You can try https://github.com/libyal/libregf/blob/master/synctestdata.sh to download test files used for CI testing.

**Comment by Anirmita** [comment]
> That is correct. You'll to create the input folder yourself and put in the test files
> 
> per https://github.com/libyal/libregf/wiki/Testing
> `Note that no test files are provided by the project.`
> 
> You can try https://github.com/libyal/libregf/blob/master/synctestdata.sh to download test files used for CI testing.

But as you can infer from the screenshot that test_regfinfo.sh and test_regfexport.sh is skipped. These files are required to be autogenerated in the input folder. How is this possible?

**Comment by joachimmetz** [comment]
I'm not sure, I fully understand what you are telling me.

* If tests/input does not exist the tests that use input files are skipped
* the test runner expects a specific directory structure as mentioned in https://github.com/libyal/libregf/wiki/Testing

**Comment by Anirmita** [comment]
> I'm not sure, I fully understand what you are telling me.
> 
>     * If tests/input does not exist the tests that use input files are skipped
> 
>     * the test runner expects a specific directory structure as mentioned in https://github.com/libyal/libregf/wiki/Testing

Exactly! The regfinfo and regfexport test profiles are skipped and i need the o/p in that format. How do I prevent it from being skipped?

**Comment by joachimmetz** [comment]
> The regfinfo and regfexport test profiles are skipped and i need the o/p in that format. How do I prevent it from being skipped?

one option is to run `./synctestdata.sh`

another option is to `mkdir tests/input` and `mkdir tests/input/testset1` then copy your test files to `tests/input/testset1`. More info about this can be found here: https://github.com/libyal/libregf/wiki/Testing
